version: '3'
services:
  app:
    image: bank-verification-java-app
    build: .
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    container_name: java_pg
    volumes:
      - bank_verification_db_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - "5450:5432"
    
volumes:
  bank_verification_db_postgres: